---
title: "TSProject_Kai"
author: "Kai Li"
date: "August 19, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r message=FALSE, warning=FALSE}
# load libraries
library(caret)
library(TSA)
library(pls)
library(forecast)
library(tseries)
library(vars)
library(MASS)
library(fpp2)
```



```{r}
df = readRDS("~/GitHub/TimeSeries-Project/TSProject/new_train.rds")

df1 = df[,10:12]
append = as.numeric(df1[,1])
kidney = as.numeric(df1[,3])

```



```{r}
ts.plot(kidney)
Acf(kidney)
```


##
```{r}

## use log rather than auto lambda
append_weekly = ts(append, frequency = 7)
kidney_weekly = ts(kidney, frequency = 7)


append_train_weekly = window(append_weekly, start = c(1,1), end = c(112,7))
append_test_weekly  = window(append_weekly, start = c(113,1), end = c(115,5))


kidney_train_weekly = window(kidney_weekly, start = c(1,1), end = c(112,7))
kidney_test_weekly  = window(kidney_weekly, start = c(113,1), end = c(115,5))


kidney_diff_train = window(diff(kidney_weekly), start = c(1,2), end = c(112,7))
kidney_diff_test = window(diff(kidney_weekly), start = c(113,1), end = c(115,5))


append_diff_train = window(diff(append_weekly), start = c(1,2), end = c(112,7))
append_diff_test = window(diff(append_weekly), start = c(113,1), end = c(115,5))


```



```{r}

append_lambda = BoxCox.lambda(append_train_weekly)
append_transformed_train = BoxCox(append_train_weekly, lambda = append_lambda)
append_transformed_test = BoxCox(append_test_weekly, lambda = append_lambda)

```



```{r}

kidney_lambda = BoxCox.lambda(kidney_train_weekly)
kidney_transformed_train = BoxCox(kidney_train_weekly, lambda = kidney_lambda)

autoplot(kidney_train_weekly)+
  autolayer(kidney_test_weekly)

kidney_transformed_test = BoxCox(kidney_test_weekly, lambda = kidney_lambda)

autoplot(kidney_transformed_train)+
  autolayer(kidney_transformed_test)

```



```{r}
adf.test(append_transformed_train) # small
kpss.test(append_transformed_train) # level is not stationary  big

adf.test(diff(append_transformed_train)) # small
kpss.test(diff(append_transformed_train)) # level is not stationary  big
plot(diff(append_transformed_train))

adf.test(diff(append_train_weekly)) # small
kpss.test(diff(append_train_weekly)) # level is not stationary  big

```


```{r}
adf.test(kidney_transformed_train)
kpss.test(kidney_transformed_train) # level is not stationary


adf.test(diff(diff(kidney_transformed_train)))
kpss.test(diff(diff(kidney_transformed_train)))
plot(diff(kidney_transformed_train))

adf.test(diff(kidney_train_weekly)) # small
kpss.test(diff(kidney_train_weekly)) # level is not stationary  big


```



```{r}
ts.plot(diff(kidney_transformed_train))
acf(diff(kidney_transformed_train))
pacf(diff(kidney_transformed_train))
```


```{r}
arima_atuo_kidney = auto.arima(kidney_transformed_train, d = 1, seasonal = T)
arima_atuo_kidney

#acf(model_auto$residuals)
#pacf(model_auto$residuals)
# Ljung-Box big
checkresiduals(arima_atuo_kidney)

pred = forecast(arima_atuo_kidney, h = 19)
inv_pred = InvBoxCox(pred$mean, lambda = kidney_lambda)
acc_atuo = accuracy(inv_pred, kidney_test_weekly)
acc_atuo
autoplot(inv_pred, include = 100)+
  autolayer(kidney_test_weekly,series = "SARIMA", color = "red")


```

```{r}
eacf(kidney_transformed_train)
```


```{r}

arima_kidney = Arima(kidney_transformed_train, order = c(1,1,2), seasonal = c(1, 0, 2))
arima_kidney

arima_kidney$coef

# Ljung-Box big
checkresiduals(arima_kidney)

pred = forecast(arima_kidney, h = 19)
inv_pred = InvBoxCox(pred$mean, lambda = kidney_lambda)
acc_arima = accuracy(inv_pred, kidney_test_weekly)
acc_arima

autoplot(inv_pred, include = 100)+
  autolayer(kidney_test_weekly,series = "SARIMA", color = "red")


```



```{r}


tbats_kidney = tbats(kidney_train_weekly)
tbats_kidney
checkresiduals(tbats_kidney)


pred = forecast(tbats_kidney, h = 19)

acc_tbats = accuracy(pred, kidney_test_weekly)
acc_tbats

autoplot(pred$mean, include = 100)+
  autolayer(kidney_test_weekly,series = "tbats", color = "red")


```



```{r}
model_arfima = arfima(kidney_transformed_train)
summary(model_arfima) 
checkresiduals(model_arfima)

pred = forecast(model_arfima, h = 19)
inv_pred = InvBoxCox(pred$mean, lambda = kidney_lambda)

acc_arfima = accuracy(inv_pred, kidney_test_weekly)
acc_arfima

autoplot(inv_pred, include = 10)+
  autolayer(kidney_test_weekly,series = "ARFIMA", color = "red")

```


```{r}

model_xreg = auto.arima(kidney_transformed_train, xreg = append_transformed_train  ,seasonal = TRUE)
model_xreg

checkresiduals(model_xreg)

pred = forecast(model_xreg, xreg = append_transformed_test, h = 19)
inv_pred = InvBoxCox(pred$mean, lambda = kidney_lambda)


acc_xreg = accuracy(inv_pred, kidney_test_weekly)
acc_xreg

autoplot(inv_pred, include = 10)+
  autolayer(kidney_test_weekly,series = "XREG", color = "red")


```


```{r}

harmonics = fourier(kidney_transformed_train, K =3)
model_fourier = auto.arima(kidney_transformed_train, xreg = harmonics, seasonal = FALSE)

checkresiduals(model_fourier)
summary(model_fourier)

new_harmonics = fourier(kidney_transformed_train, K =3, h = 19)
pred = forecast(model_fourier, xreg = new_harmonics)

inv_pred = InvBoxCox(pred$mean, lambda = kidney_lambda)
acc_fourier = accuracy(inv_pred, kidney_test_weekly)
acc_fourier


autoplot(inv_pred, include = 10)+
  autolayer(kidney_test_weekly,series = "SARIMA", color = "red")
```



```{r}
# VAR model

var_data = window(ts.union(diff(kidney_transformed_train), diff(append_transformed_train)))

model_var = VAR(y = var_data, p = 2)
model_var

pred = forecast(model_var, h = 19)
pred_kidney = pred$forecast$diff.kidney_transformed_train.$mean
pred_kidney = ts(pred_kidney, start = c(113,1), end = c(115,5), frequency = 7)

act_pred = append(kidney_transformed_train[784],pred_kidney)
act_pred = cumsum(act_pred)
act_pred = act_pred[2:20]
inv_pred = InvBoxCox(act_pred, lambda = kidney_lambda)
inv_pred = ts(inv_pred, start = c(113,1), end = c(115,5), frequency = 7)
accuracy(inv_pred, kidney_test_weekly)


autoplot(inv_pred, include = 100)+
  autolayer(kidney_test_weekly,series = "SARIMA", color = "red")

```


```{r}
aicc <- cbind(auto_arima=arima_atuo_kidney$aicc, model_Arima=arima_kidney$aicc, TBATS = tbats_kidney$AIC,
              model_arfima=summary(model_arfima)$aic, fourier = model_fourier$aicc , xreg=model_xreg$aicc) 
aicc
sort(aicc)

rmse <- c(auto_arima=acc_atuo[,2], model_Arima=acc_arima[,2], TBATS = acc_tbats[,2],
              model_arfima=acc_arfima[,2], fourier = acc_fourier[,2] , xreg=acc_xreg[,2])
rmse 

data <- rbind(aicc,rmse)
comparison <- as.data.frame(t(data),row.name=c('Auto_arima','SARIMA','TBATS','ARFIMA','Fourier', 'Regression with arima error'))
colnames(comparison)<-c('AICC', 'RMSE')
comparison[order(comparison$RMSE),]
```


